export const BeaconHostelsTeam = [
  {
    name: "Samuel Wekobosya",
    role: "C.T.O",
    url: "",
    fb: "",
    twitter: "",
    linkedin: "",
    email: "samweko@gmail.com",
    github: "https://github.com/17Xamuel",
    whatsapp: "",
  },
  {
    name: "Aggi Peter Odaak",
    role: "Web Developer",
    url: "https://firebasestorage.googleapis.com/v0/b/beacon-hostels.appspot.com/o/Team-images%2FWhatsApp%20Image%202023-05-05%20at%206.15.46%20PM.jpeg?alt=media&token=1f741d75-167a-466e-ad58-416dc8591ce4",
    fb: "https://www.facebook.com/aggi.peter.98",
    twitter: "https://twitter.com/aggipeters",
    linkedin: "https://www.linkedin.com/in/aggi-peter-817921219/",
    email: "aggipeter25@gmail.com",
    github: "https://github.com/peteraggi",
    whatsapp: "",
  },
  {
    name: "Kugumikiriza Andrew",
    role: "Graphics Designer",
    url: "https://firebasestorage.googleapis.com/v0/b/beacon-hostels.appspot.com/o/Team-images%2Fmy%20pp2.jpg?alt=media&token=067a411b-a1a9-4499-8cf3-673b9973dfb4",
    fb: "https://www.facebook.com/kugumikiriza.andrew.9",
    twitter: "https://twitter.com/AndyReign126?s=08",
    linkedin:
      "https://www.linkedin.com/in/kugumikiriza-andrew-6b6a61224?trk=contact-info",
    email: "",
    github: "",
    whatsapp: "",
  },
  {
    name: "Nahurira Gaston",
    role: "C.E.O",
    url: "https://firebasestorage.googleapis.com/v0/b/beacon-hostels.appspot.com/o/Team-images%2Fgj-01.png?alt=media&token=c9330e32-797d-4e80-bcab-277a96be0222",
    fb: "https://www.facebook.com/nahurira.gaston.7",
    twitter: "https://twitter.com/gaston_lyte?t=altqfWvEkAV3kT9kBTJu0Q&s=09",
    linkedin: "",
    email: "",
    github: "https://github.com/gastoncodes",
    whatsapp: "",
  },
  {
    name: "Obua Jonnathan",
    role: "Head Of Marketing",
    url: "",
    fb: "",
    twitter: "",
    linkedin: "",
    email: "",
    github: "",
    whatsapp: "",
  },
];
